RMTP-69 Update APIs to use Assembly and Type instead of _Assembly and  _Type reflection APIs
re-motion/TypePipe pull request #14
Opened 2021-05-07 11:59 UTC by raffaelfoidl

https://re-motion.atlassian.net/browse/RMTP-69

2021-05-10 14:38 UTC, iam-mholle requested changes

2021-05-10 14:38 UTC, iam-mholle commented on Core/Implementation/CodeManager.cs
>      [CLSCompliant (false)]
Assembly is `CLSCompliant`, please remove the attribute :)

2021-05-11 11:17 UTC, iam-mholle approved these changes

2021-05-12 07:06 UTC, MichaelKetting approved these changes

2021-05-12 07:48 UTC, merged